-- Required trigger: keeps rw_messages.search_vector in sync with the
-- content on every INSERT/UPDATE, so full-text search (see
-- queries/02_search_messages_highlight.sql) is never stale.
--
-- The vector embedding (RAG) is NOT generated by this trigger: producing
-- it requires calling the OpenAI API, which cannot happen synchronously
-- inside a Postgres transaction. The backend computes it after inserting
-- the message and persists it with an explicit UPDATE (see
-- infrastructure/ai in the backend). What the trigger DOES guarantee is
-- consistency: when the content of an already-embedded message changes,
-- the old embedding no longer describes it, so it is cleared here and the
-- backend re-embeds it asynchronously. A stale embedding is worse than a
-- missing one -- rw_fn_copilot_context skips NULL embeddings, so a cleared
-- row simply drops out of semantic retrieval until re-embedded.
CREATE OR REPLACE FUNCTION rw_fn_messages_search_vector()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.search_vector := to_tsvector('english', NEW.content);
  IF TG_OP = 'UPDATE' AND NEW.content IS DISTINCT FROM OLD.content THEN
    NEW.embedding := NULL;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER rw_trg_messages_search_vector
  BEFORE INSERT OR UPDATE OF content ON rw_messages
  FOR EACH ROW
  EXECUTE FUNCTION rw_fn_messages_search_vector();
